#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     c1,             sensorI2CMuxController)
#pragma config(Sensor, S2,     c2,             sensorI2CMuxController)
#pragma config(Sensor, S3,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C2_1,     frontleft,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     backleft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     frontright,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     backright,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     central,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     winch,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     arm1,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     arm2,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    armservo,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    bucket1,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    bucket2,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

    /*
    | ------------------------------------------------------------------------------
    | Teleop Code for FTC Team 6547 Cobalt Colts, 2014 Red Hummingbird
    | Test code for preparation for FRC Demo
    | Winch is now flag but not renaming
    | Written primarily by head programmer, Ryan Pope
    | Thanks to Sean Doyle, Doc Tassio and Eric Briscoe for their contributions
    | Also thanks to Ben, Ethan, Lex and Jarren for their autonomous
    | Thanks to Tony Ma for driving this robot
    | Thanks to Allison Meegan and Surabhi for their leadership
    | Thanks to Lily for being awesome and nice and pretty
    | Thanks to builders and Joe for having a robot to program
    | ® All rights reserved Team 6547
    | ------------------------------------------------------------------------------
    */

#include "JoystickDriver.c"

    /*
    | ------------------------------------------------------------------------------
    | Controller buttons
    | ------------------------------------------------------------------------------
    */

    int x = 1; int a = 2; int b = 3; int y = 4;     /* Buttons                    */
    int leftBumper = 5; int rightBumper = 6;        /* bumpers                    */
    int leftTrigger = 7; int rightTrigger = 8;      /* triggers                   */
    //int input = joystick.joy2_y2; int sign = input / abs(input); int output = sign*(100*input**2)/16384;

	task main() {

        waitForStart();

        while (true)
        {
            getJoystickSettings(joystick);              /* Updates Joystick settings  */

            /*
            | --------------------------------------------------------------------------
            | Joystick control
            | --------------------------------------------------------------------------
            */
            motor[frontleft]        = joystick.joy1_y1 * 100 / 128;
            motor[frontright]       = joystick.joy1_y2 * 100 / 128;
            motor[backleft]         = joystick.joy1_y1 * 100 / 128;
            motor[backright]        = joystick.joy1_y2 * 100 / 128;

            /*
            | --------------------------------------------------------------------------
            | Center wheel control code
            | --------------------------------------------------------------------------
            */

            if (joy1Btn(rightBumper) == 1) {
                motor[central] = -100;
            } else if (joy1Btn(leftBumper) == 1) {
                motor[central] = 100;
            } else {
                motor[central] = 0;
            }

            /*
            | --------------------------------------------------------------------------
            | Flag control code
            | --------------------------------------------------------------------------
            */

            if (joy2Btn(leftBumper) == 1) {
                motor[winch]=100;
            } else if (joy2Btn(rightBumper) == 1) {
                motor[winch]=-100;
            } else {
                motor[winch]=0;
            }

            /*
            | --------------------------------------------------------------------------
            | Arm Control Code
            | --------------------------------------------------------------------------
            */

            motor[arm1] = joystick.joy2_y2/3;
            motor[arm2] = joystick.joy2_y2/3;

            /*
            | --------------------------------------------------------------------------
            | Arm Servo Control Code
            | --------------------------------------------------------------------------
            */
						if (joy2Btn(a) == 1) {
                servo[arm1] = 0;
                servo[arm2] = 0;
            } else if (joy2Btn(x) == 1) {
                servo[arm1] = 255;
                servo[arm2] = 255;
            }

        }

}
