#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     c1,             sensorNone)
#pragma config(Sensor, S2,     c2,             sensorNone)
#pragma config(Sensor, S3,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     touch,          sensorTouch)
#pragma config(Motor,  motorA,          flap1,         tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          flap2,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     frontleft,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     backleft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     frontright,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     backright,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     central,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     winch,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     arm,           tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    armservo,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    rachetservo,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

    /*
    | ------------------------------------------------------------------------------
    | Controller buttons
    | ------------------------------------------------------------------------------
    */
    
    int x = 1; int a = 2; int b = 3; int y = 4;     /* Buttons                    */
    int leftBumper = 5; int rightBumper = 6;        /* bumpers                    */
    int leftTrigger = 7; int rightTrigger = 8;      /* triggers                   */
	/*int armDrive(){
		/*if(joystick.joy2_y1 < 15 && joystick.joy2_y1 > -15){
			if(nMotorEncoder[arm] < 400 && nMotorEncoder[arm] > -320) {
                motor[arm] = -10;
			} else if (nMotorEncoder[arm] < -320 && nMotorEncoder[arm] > q){
                motor[arm] = 10;
            }
		}else{
			motor[arm] = joystick.joy2_y1 / 5;
		//}
		return motor[arm];
	}*/

	task main() {
    //This code was written by Ryan Pope.
    //Sean is the bonaestest programmer.
    waitForStart();


    while (true)
    {
    		nMotorEncoder[arm] = 0;
    		//nxtDisplayBigTextLine(3, "%d", nMotorEncoder[arm]);
    		wait1Msec(50);

        //servoChangeRate[armservo] = 2;              /* Slows the servo            */
        getJoystickSettings(joystick);              /* Updates Joystick settings  */

        /*
        | --------------------------------------------------------------------------
        | Joystick control
        | --------------------------------------------------------------------------
        */
        motor[frontleft]        = joystick.joy1_y1 * 100 / 128;
        motor[frontright]       = joystick.joy1_y2 * 100 / 128;
        motor[backleft]         = joystick.joy1_y1 * 100 / 128;
        motor[backright]        = joystick.joy1_y2 * 100 / 128;
        //motor[arm]              = armDrive();
	
        /*
        | --------------------------------------------------------------------------
        | Center wheel control code
        | --------------------------------------------------------------------------
        */
        if (joy1Btn(rightBumper) == 1) {
            motor[central] = -100;
        } else if (joy1Btn(leftBumper) == 1) {
            motor[central] = 100;
        } else {
            motor[central] = 0;
        }

        /*
        | --------------------------------------------------------------------------
        | Arm servo control code (Likely to change)
        | --------------------------------------------------------------------------

        if (joy2Btn(a) == 1) {
            servo[armservo] += 20;
        } else if (joy2Btn(y) == 1) {
            servo[armservo] -= 20;
        } else {
        		servo[armservo] += 0;
      	}
				*/
	| --------------------------------------------------------------------------
        | Rachet servo control code (Added by Briscoe at last minute)
        | --------------------------------------------------------------------------

        if (joy1Btn(a) == 1) {
            servo[armservo] += 5;
        } else if (joy1Btn(b) == 1) {
            servo[armservo] -= 5;
        } else {
        		servo[armservo] += 0;
      	}
        /*
        | --------------------------------------------------------------------------
        | Pickup roller control code
        | --------------------------------------------------------------------------
        */
        if (joy2Btn(leftTrigger) == 1) {
            motor[flap1] = -100;
            motor[flap2] = 100;
        } else if (joy2Btn(rightTrigger) == 1) {
            motor[flap1] = 100;
            motor[flap2] = -100;
        } else {
            motor[flap1] = 0;
            motor[flap2] = 0;
        }

        /*
        | --------------------------------------------------------------------------
        | Winch control code
        | --------------------------------------------------------------------------
        */
        if (joy2Btn(leftBumper) == 1) {
            motor[winch]=75;
        } else if (joy2Btn(rightBumper) == 1) {
            motor[winch]=-75;
        } else {
            motor[winch]=0;
        }
    }

}
